periodical:
  #!!!DO NOT CHANGE DATE MANUALLY!!!
  date: 2100-01-01=00:00:00.001+09:00
  interval: 10080
  worlds:
    - TEST

command:
  before:
    - say Start regenerating %world%
  after:
    - say Finish regenerating %world%

tp-world: world