periodical:
  #!!!DO NOT CHANGE DATE MANUALLY!!!
  date: 2100-01-01T00:00:00.000+09:00
  interval: 3
  worlds:
    - TEST

command:
  before:
    - say Start regenerating %world%
  after:
    - say Finish regenerating %world%

tp-world: world